_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 64
beta:
    value: 0.25
embedding_dim:
    value: 64
hidden_dim:
    value: 256
learning_rate:
    value: 0.000225
num_embeddings:
    value: 512
num_epochs:
    value: 10
